n_epochs:       100       # number of epochs with the initial learning rate
n_epochs_decay: 100       # number of epochs to linearly decay learning rate to zero
beta1_G:        0.5       # momentum term of adam for generator
beta1_D:        0.5       # momentum term of adam for discriminator
lr_G:           0.0002    # initial learning rate for adam for generator
lr_D:           0.0002    # initial learning rate for adam for discriminator
gan_mode:       'lsgan'   # the type of GAN objective. [vanilla| lsgan | wgangp]. vanilla GAN loss is the cross-entropy objective used in the original GAN paper.
pool_size:      50        # the size of image buffer that stores previously generated images
lr_policy:      'linear'  # learning rate policy. [linear | step | plateau | cosine]
lr_decay_iters: 50        # multiply by a gamma every lr_decay_iters iterations
