n_epochs:         100       # number of epochs with the initial learning rate
n_epochs_decay:   100       # number of epochs to linearly decay learning rate to zero
beta1:            0.5       # momentum term of adam
lr:               0.0002    # initial learning rate for adam
gan_mode:         'lsgan'   # the type of GAN objective. [vanilla| lsgan | wgangp]. vanilla GAN loss is the cross-entropy objective used in the original GAN paper.
lambda_A:         10.0      # weight for cycle loss (A -> B -> A)
lambda_B:         10.0      # weight for cycle loss (B -> A -> B)
lambda_identity:  0.5      # use identity mapping. Setting lambda_identity other than 0 has an effect of scaling the weight of the identity mapping loss. For example, if the weight of the identity loss should be 10 times smaller than the weight of the reconstruction loss, please set lambda_identity = 0.1

pool_size:        50        # the size of image buffer that stores previously generated images
lr_policy:        'linear'  # learning rate policy. [linear | step | plateau | cosine]
lr_decay_iters:   50        # multiply by a gamma every lr_decay_iters iterations
