hydra:
  job:
    chdir: true
  run:
    dir: outpus/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}
defaults:
  - base@_global_:
    - basic
    - dataset
    - model
    - additional
    - wandb
    - mlflow
  - train@_global_:
    - training
    - network
    - visualize
isTrain:          true
