hydra:
  run:
    dir: multirun/${name}/${hydra.job.override_dirname}
defaults:
  - base@_global_:
    - basic
    - dataset
    - model
    - additional
    - wandb
    - mlflow
  - train@_global_:
    - training
    - network
    - visualize
isTrain:          true
