hydra:
  job:
    chdir: true
  run:
    dir: outputs/${name}/${my_override_dirname:${hydra.overrides}}
  sweep:
    dir: multirun/${name}
    subdir: ${my_override_dirname:${hydra.overrides}}
defaults:
  - base
  - model:          cycle_gan
  - visualizer:     [visdom,mlflow]
  - train_defaults
  - _self_

dataroot:         'datasets/colbase_dataset_4096x2048'
name:             'colbase_test_after_options2yaml'
load_size:        1054
crop_size:        1024
n_epochs:         5
n_epochs_decay:   5

