dataset_mode:     'unaligned'       # chooses how datasets are loaded. [unaligned | aligned | single | colorization]
direction:        'AtoB'            # AtoB or BtoA
serial_batches:   false             # if true, takes images in order to make batches, otherwise takes them randomly
num_threads:      4                 # # threads for loading data
batch_size:       1                 # input batch size
load_size:        286               # scale images to this size
crop_size:        256               # then crop to this size
max_dataset_size: 65536             # Maximum number of samples allowed per dataset. If the dataset directory contains more than max_dataset_size, only a subset is loaded.
preprocess:       'resize_and_crop' # scaling and cropping of images at load time [resize_and_crop | crop | scale_width | scale_width_and_crop | none]
no_flip:          false             #  if specified, do not flip the images for data augmentation
display_winsize:  256               # display window size for both visdom and HTML
